# Generated by Django 5.1 on 2024-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=128)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('jefe', 'Jefe de Ventas'), ('vendedor', 'Vendedor')], max_length=10)),
            ],
        ),
    ]
